# Codemagic CI/CD Configuration for CarePoint
# Documentation: https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  # ═══════════════════════════════════════════════════════════════
  # iOS Build & TestFlight
  # ═══════════════════════════════════════════════════════════════
  ios-workflow:
    name: iOS Build & TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.carepoint.drsjad
      vars:
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          
      - name: Set up code signing
        script: |
          xcode-project use-profiles
          
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

  # ═══════════════════════════════════════════════════════════════
  # Android Build & Play Store
  # ═══════════════════════════════════════════════════════════════
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: linux_x2

    environment:
      flutter: stable
      java: 17

    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Build APK
        script: flutter build apk --release
        
      - name: Build App Bundle
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
